/* ══════════════════════════════════════════
   Digital Moroccan casino — Game Catalog (22 Games)
   ══════════════════════════════════════════ */
"use strict";
const GAMES = [
  /* ═══ تقليدية ═══ */
  {
    id: 'rn',
    eng: 'ronda',
    em: '♦️♠️',
    art: 'rn',
    cat: 'traditional',
    tag: 'HOT',
    rtp: 95,
    pl: 312,
    n: 'Moroccan Ronda ♦️♠️',
    d: ['40 ورقة مغاربية', '40 cartes', '40 cards']
  },
  {
    id: 'pr',
    eng: 'parchisi',
    em: '🎲',
    art: 'rn',
    cat: 'traditional',
    tag: 'NEW',
    rtp: 95,
    pl: 156,
    n: 'Parchisi',
    d: ['لعبة الطاولة الهندية', 'Jeu de société', 'Classic board game']
  },
  /* ═══ كراش ═══ */
  {
    id: 'av',
    eng: 'crash',
    em: '🚀',
    art: 'cr',
    cat: 'crash',
    tag: 'HOT',
    rtp: 97,
    pl: 892,
    n: 'Aviator Crash',
    d: ['منحنى حي', 'Courbe live', 'Live curve']
  },
  /* ═══ فورية ═══ */
  {
    id: 'mn',
    eng: 'mines',
    em: '💣',
    art: 'in',
    cat: 'instant',
    tag: 'HOT',
    rtp: 97,
    pl: 720,
    n: 'Mines',
    d: ['تجنب الألغام', 'Évitez les mines', 'Avoid mines']
  },
  {
    id: 'pl',
    eng: 'plinko',
    em: '⚪',
    art: 'in',
    cat: 'instant',
    tag: 'HOT',
    rtp: 98,
    pl: 534,
    n: 'Plinko',
    d: ['فيزياء كرة', 'Physique réelle', 'Ball physics']
  },
  {
    id: 'dc',
    eng: 'dice',
    em: '🎲',
    art: 'in',
    cat: 'instant',
    tag: 'LIVE',
    rtp: 98,
    pl: 411,
    n: 'Dice',
    d: ['هدف متحرك', 'Cible réglable', 'Target']
  },
  {
    id: 'cf',
    eng: 'coin',
    em: '🪙',
    art: 'in',
    cat: 'instant',
    tag: 'NEW',
    rtp: 97.5,
    pl: 265,
    n: 'Coin Flip 3D',
    d: ['عملة 3D', 'Pièce 3D', '3D coin']
  },
  {
    id: 'hl',
    eng: 'hilo',
    em: '🃏',
    art: 'in',
    cat: 'instant',
    tag: 'LIVE',
    rtp: 95.4,
    pl: 342,
    n: 'Hi-Lo Cards',
    d: ['أعلى/أقل', 'Plus haut/bas', 'Higher/lower']
  },
  {
    id: 'wf',
    eng: 'wheel',
    em: '🎡',
    art: 'in',
    cat: 'instant',
    tag: 'HOT',
    rtp: 97.5,
    pl: 456,
    n: 'Wheel of Fortune',
    d: ['12 مضاعفاً', '12 multiplicateurs', '12 multipliers']
  },
  {
    id: 'sc',
    eng: 'scr',
    em: '🎫',
    art: 'in',
    cat: 'instant',
    tag: 'NEW',
    rtp: 94,
    pl: 187,
    n: 'Scratch Card',
    d: ['اكشف 3', '3 identiques', 'Match 3']
  },
  {
    id: 'wg',
    eng: 'wingo',
    em: '🌈',
    art: 'in',
    cat: 'instant',
    tag: 'LIVE',
    rtp: 95,
    pl: 398,
    n: 'Wingo Colors',
    d: ['ألوان', 'Couleurs', 'Colors']
  },
  {
    id: 'rp',
    eng: 'rps',
    em: '✊',
    art: 'in',
    cat: 'instant',
    tag: 'NEW',
    rtp: 98.3,
    pl: 154,
    n: 'Rock Paper Scissors',
    d: ['ضد الحاسوب', 'vs IA', 'vs AI']
  },
  {
    id: 'pn',
    eng: 'pen',
    em: '⚽',
    art: 'in',
    cat: 'instant',
    tag: 'HOT',
    rtp: 96.7,
    pl: 276,
    n: 'Penalty Shootout',
    d: ['حارس متحرك', 'Gardien', 'Keeper']
  },
  {
    id: 'l7',
    eng: 'l7',
    em: '7️⃣',
    art: 'in',
    cat: 'instant',
    tag: 'LIVE',
    rtp: 94.8,
    pl: 203,
    n: 'Lucky 7',
    d: ['كرة 1-9', 'Boule 1-9', 'Ball 1-9']
  },
  /* ═══ كازينو ═══ */
  {
    id: 'sb',
    eng: 'sicbo',
    em: '🎲',
    art: 'rl',
    cat: 'casino',
    tag: 'LIVE',
    rtp: 97,
    pl: 145,
    n: 'Sic Bo',
    d: ['نرد متدحرج', 'Dés animés', 'Rolling dice']
  },
  {
    id: 'rl',
    eng: 'rl',
    em: '🎯',
    art: 'rl',
    cat: 'casino',
    tag: 'HOT',
    rtp: 97,
    pl: 412,
    n: 'European Roulette',
    d: ['كرة دوّارة', 'Bille orbitale', 'Orbiting ball']
  },
  /* ═══ ورق ═══ */
  {
    id: 'bj',
    eng: 'bj',
    em: '🃏',
    art: 'bj',
    cat: 'card',
    tag: 'HOT',
    rtp: 98,
    pl: 256,
    n: 'Blackjack 21',
    d: ['ضد الموزع', 'vs croupier', 'vs dealer']
  },
  {
    id: 'bc',
    eng: 'bac',
    em: '🃏',
    art: 'bj',
    cat: 'card',
    tag: 'LIVE',
    rtp: 96,
    pl: 187,
    n: 'Baccarat',
    d: ['لاعب/موزع', 'Joueur/Banquier', 'Player/Banker']
  },
  {
    id: 'dt',
    eng: 'dt',
    em: '🐉',
    art: 'bj',
    cat: 'card',
    tag: 'LIVE',
    rtp: 96,
    pl: 165,
    n: 'Dragon Tiger',
    d: ['بطاقتان', '2 cartes', '2 cards']
  },
  {
    id: 'vp',
    eng: 'vp',
    em: '🂠',
    art: 'pk',
    cat: 'card',
    tag: 'NEW',
    rtp: 97,
    pl: 132,
    n: 'Video Poker',
    d: ['Jacks or Better', 'Jacks or Better', 'Jacks or Better']
  },
  {
    id: 'ke',
    eng: 'keno',
    em: '🔢',
    art: 'keno',
    cat: 'keno',
    tag: 'LIVE',
    rtp: 94,
    pl: 189,
    n: 'Keno',
    d: ['20 من 80', '20 sur 80', '20 of 80']
  },
  {
    id: 'sl',
    eng: 'slots',
    em: '🎰',
    art: 'slots',
    cat: 'slots',
    tag: 'HOT',
    rtp: 95.9,
    pl: 342,
    n: 'Royal Slots',
    d: ['3 بكرات', '3 rouleaux', '3 reels']
  },
  {
    id: 'ab',
    eng: 'andarbahar',
    em: '🃏',
    art: 'bj',
    cat: 'card',
    tag: 'NEW',
    rtp: 95,
    pl: 134,
    n: 'Andar Bahar',
    d: ['أندار أم باهار', 'Andar ou Bahar', 'Andar or Bahar']
  },
  /* ═══ جديدة ═══ */
  {
    id: 'crabbin',
    eng: 'crabbin',
    em: '🦀',
    art: 'crabbin',
    cat: 'instant',
    tag: 'NEW',
    rtp: 94.4,
    pl: 0,
    n: 'Crabbin',
    d: ['9 سرطانات: 6 ذهبية و3 حمراء', 'Jeu de crabes', 'Crab game']
  },
  {
    id: 'fishing',
    eng: 'fishing',
    em: '🎣',
    art: 'fishing',
    cat: 'instant',
    tag: 'NEW',
    rtp: 95.5,
    pl: 0,
    n: 'Fishing',
    d: ['اصطد السمكة بالمضاعف', 'Pêche aux multiplicateurs', 'Fishing multipliers']
  },
  {
    id: 'gates',
    eng: 'gates',
    em: '⛩️',
    art: 'gates',
    cat: 'instant',
    tag: 'NEW',
    rtp: 95,
    pl: 0,
    n: 'Gates',
    d: ['بوابات زيوس الذهبية', 'Portes de Zeus', 'Gates of Zeus']
  },
  {
    id: 'lightning',
    eng: 'lightning',
    em: '⚡',
    art: 'lightning',
    cat: 'instant',
    tag: 'NEW',
    rtp: 95.8,
    pl: 0,
    n: 'Lightning',
    d: ['برق ذهبي يحقق الجائزة', 'Éclair doré', 'Golden lightning']
  },
  {
    id: 'lottery',
    eng: 'lottery',
    em: '🎟️',
    art: 'lottery',
    cat: 'instant',
    tag: 'NEW',
    rtp: 95,
    pl: 0,
    n: 'Lottery',
    d: ['تذاكر يانصيب محظوظة', 'Billets de loterie', 'Lucky lottery']
  },
  {
    id: 'mahjong',
    eng: 'mahjong',
    em: '🀄',
    art: 'mahjong',
    cat: 'instant',
    tag: 'NEW',
    rtp: 95,
    pl: 0,
    n: 'Mahjong',
    d: ['بلاطات الحظ الصينية', 'Tuiles de chance chinoises', 'Lucky mahjong tiles']
  },
  {
    id: 'money',
    eng: 'money',
    em: '💰',
    art: 'money',
    cat: 'instant',
    tag: 'NEW',
    rtp: 94.4,
    pl: 0,
    n: 'Money',
    d: ['صناديق الكنوز', 'Coffres aux trésors', 'Golden money safes']
  },
  {
    id: 'olympus',
    eng: 'olympus',
    em: '🏛️',
    art: 'olympus',
    cat: 'instant',
    tag: 'NEW',
    rtp: 95,
    pl: 0,
    n: 'Olympus',
    d: ['قوة آلهة الأوليمب', 'Puissance des dieux', 'Power of Olympus gods']
  },
  {
    id: 'poker',
    eng: 'poker',
    em: '🃏',
    art: 'poker',
    cat: 'casino',
    tag: 'NEW',
    rtp: 95,
    pl: 0,
    n: 'Poker',
    d: ['البطاقات الملكية للبوكر', 'Cartes royales du poker', 'Royal poker cards']
  },
  {
    id: 'rose',
    eng: 'rose',
    em: '🌹',
    art: 'rose',
    cat: 'instant',
    tag: 'NEW',
    rtp: 95,
    pl: 0,
    n: 'Rose',
    d: ['وردة الحظ الذهبية', 'Rose dorée de la chance', 'Golden lucky rose']
  },
  {
    id: 'sweet-bonanza',
    eng: 'sweet-bonanza',
    em: '🍬',
    art: 'sweet-bonanza',
    cat: 'instant',
    tag: 'NEW',
    rtp: 95,
    pl: 0,
    n: 'Sweet Bonanza',
    d: ['حلوى سكرية محظوظة', 'Bonbons sucrés chanceux', 'Sweet candy bonanza']
  }
];
/* ── قواعد مختصرة داخل اللعبة ── */
const RULES = {
  crabbin: [['اضغط ابدأ ثم اختر سلطعوناً واحداً', '6 سرطانات ذهبية ×1.3-×1.6 و3 حمراء تخسر', 'الذهبي ×1.3/×1.3/×1.4/×1.4/×1.5/×1.6 — RTP 94.4%']],
  fishing: [['اختر سمكة وأطلق القذيفة', 'كلما كبر المضاعف قلّ احتمال الاصطياد', '×1.1 (90%) حتى ×3 (35%) — RTP 95.5%']],
  gates: [['اضغط ابدأ ثم افتح بوابة واحدة', '3 بوابات ذهبية ×1.2/×1.3/×1.3 وبوابة ملعونة ×0', 'بوابة ذهبية تربح — RTP 95%']],
  lightning: [['اضغط ابدأ ثم اختر شرارة', '9 برقات ×1.1-×1.5 و3 عواصف تخسر', 'برق ذهبي يضاعف رهانك — RTP 95.8%']],
  lottery: [['اضغط ابدأ ثم اختر تذكرة', '3 تذاكر رابحة ×1.4/×1.9/×2.4 و3 فارغة', 'تذكرة رابحة تربح — RTP 95%']],
  mahjong: [['اضغط ابدأ ثم اختر بلاطة واحدة', '8 بلاطات ذهبية ×1.3-×1.6 و4 حمراء تخسر', 'البلاطة الذهبية تربح — RTP 95%']],
  money: [['اضغط ابدأ ثم اختر خزنة واحدة', '6 خزائن ذهبية ×1.3-×1.6 و3 قنابل تخسر', 'الخزنة الذهبية تربح — RTP 94.4%']],
  olympus: [['اضغط ابدأ ثم اختر إلهاً واحداً', '3 آلهة ذهبية ×1.2/×1.3/×1.3 وإله ملعون ×0', 'الإله الذهبي يضاعف رهانك — RTP 95%']],
  poker: [['اضغط ابدأ ثم اختر بطاقة واحدة', '3 بطاقات ملكية A/K/Q و2 منخفضتان تخسران', 'البطاقة الملكية تربح — RTP 95%']],
  rose: [['اضغط ابدأ ثم اختر وردة واحدة', '4 وردات ذهبية ×1.2-×1.7 وصبارتان تخسران', 'الوردة الذهبية تربح — RTP 95%']],
  "sweet-bonanza": [['اضغط ابدأ ثم اختر حلوى واحدة', '8 حلوى ×1.2-×1.8 و4 قنابل تخسر', 'الحلوى الذهبية تربح — RTP 95%']],
  rn: [['اختر رقماً (1-12) أو رقماً + رمزاً', 'سحب بالتناوب مع الموزع', 'أول من يجد بطاقته يفوز']],
  av: [['اضغط ابدأ ليقلع المضاعف', 'اسحب قبل التحطم', 'كلما انتظرت أكثر زاد الربح']],
  mn: [['اختر عدد الألغام', 'افتح الخانات الآمنة', 'اسحب قبل لغم']],
  ab: [['اختر Andar أو Bahar', 'يتم السحب بالتناوب — أول بطاقة بنفس رتبة الجوكر تفوز', 'كلا الجانبين ×1.9 — RTP 95%']],
  sb: [['صغير (4-10) أو كبير (11-17) يدفع ×2', 'تريبل (3 نردات متطابقة) يدفع ×30', 'التريبلات مستثناة من الصغير والكبير']],
  rl: [['أحمر / أسود / زوجي / فردي / نطاقات تدفع ×2', 'أخضر (0) يدفع ×14', 'اضغط دَوِّر وانتظر استقرار الكرة']],
  bc: [['اللاعب أو البنك أو تعادل', 'الأقرب إلى 9 يفوز (الآس = 1، الصور = 0)', 'اللاعب ×2 / البنك ×1.95 / التعادل ×9']],
  dt: [['تنين أو نمر — الأعلى قيمة يفوز ×2', 'الآس أعلى من الملك', 'التعادل (نفس القيمة) يدفع ×11']],
  vp: [['توزيع 5 بطاقات، احجز الجيدة منها', 'ارسم لاستبدال الباقي', 'زوج J أو أعلى يبدأ الدفع']],
  sc: [['6 خلايا آمنة 💎 و3 ألغام 💣 مخفية', 'كشف اللغم = خسارة الرهان', 'كشف كل الماسات = ×80']],
  ke: [['اختر 1-10 أرقام من 1 إلى 80', 'يُسحب 20 رقماً عشوائياً', 'المضاعفات حسب المطابقات والأرقام المختارة']],
  pl: [['اختر 8 / 10 / 12 / 16 صفاً ثم أفلت الكرة', 'قرار عشوائي عند كل صف (توزيع ثنائي)', 'مضاعفات الأطراف ضخمة والوسط صغير — RTP 95%']],
  dc: [['اضبط الهدف (1-98) واختر أقل من ⬇ أو فوق ⬆', 'النتيجة 0.00-99.99 — اربح إذا تحقق شرطك', 'المضاعف = 98 ÷ الاحتمال — RTP 98%']],
  wf: [['12 قطاعاً موزوناً — 6 رابحة من 12', 'الدفع = الرهان × المضاعف (×0 خسارة، ×1 استرداد)', 'المضاعفات الكبيرة نادرة — RTP 97.5%']],
  hl: [['خمّن أعلى ↑ أو أقل ↓ من البطاقة الحالية', 'تخمين صحيح يدفع ×1.9', 'تعادل = استرداد — RTP 95.4%']],
  wg: [['اختر لوناً — أحمر ×1.9 / أخضر ×2.85 / أزرق ×5.7', 'الكرة تُسحب من 6 كرات موزونة (أحمر 3، أخضر 2، أزرق 1)', 'مطابقة اللون تربح — RTP 95%']],
  cf: [['اختر 🦁 أو 👑', 'قلب العملة يكشف الوجه — احتمال 50%', 'الصحيح يدفع ×1.95 — RTP 97.5%']],
  rp: [['اختر ✊ حجر أو ✋ ورقة أو ✌️ مقص', 'الحاسوب يختار عشوائياً في نفس اللحظة', 'فوز ×1.95 / تعادل = استرداد / خسارة — RTP 98.3%']],
  pn: [['اختر ⬅️ يسار أو ⬆️ وسط أو ➡️ يمين', 'الحارس يختار عشوائياً في نفس اللحظة', 'فوز ×1.45 / نفس الجهة = تصدي وخسارة — RTP 96.7%']],
  l7: [['اختر <7 (1-6) أو =7 أو >7 (8-9)', 'كُرة مرقمة 1-9 تُسحب عشوائياً', '<7 ×1.4 / =7 ×8.6 / >7 ×4.3 — RTP 94.8%']],
  sl: [['3 بكرات × 8 رموز متساوية الاحتمال', '3 متطابقة = جاكبوت (×120 أقصى) / 2 متطابقة = استرداد', 'الرهان يُسحب ثم يدفع عند الفوز — RTP 95.9%']]
};

/* ── Export to global ────────────────── */
window.GAMES = GAMES;
window.RULES = RULES;